/**
 * questions.js
 * Full question dataset — rearranged/cleaned:
 * - Exact duplicates that were repeated in EXERCISE_OSI_TCP_IP (and already present in OSI_DATA_COMMS)
 * were removed from EXERCISE_OSI_TCP_IP so each question appears in the most appropriate category only.
 * - LAW_ALL and ALL are constructed from the single source arrays to avoid duplication.
 * - Added MOCK_BOARD_MATH and MOCK_BOARD_EST categories.
 * - Cleaned up LaTeX syntax in Mock Board questions for readability.
 */

window.QUIZ_DATA = (function () {
  const data = {

    OSI_DATA_COMMS: [
      { q: "Which standards body created the cables and connector specifications used to support Ethernet implementation?", a: "ΕΙΑ/ΤΙΑ", options: ["ΕΙΑ/ΤΙΑ", "ISO", "ANSI", "IETF"] },
      { q: "What do TIA/EIA stand for?", a: "Telecommunications Industry Association/ Electronic Industries Alliance", options: ["Telephone International Association/Electronic Industries Alliance", "Telecommunications Industry Alliance/Electronic Industries Association", "Telecommunications Industry Association/ Electronic Industries Alliance", "Television Industry Association/Electronic Industries Association"] },
      { q: "Which data flow or transmission mode allows for unidirectional flow of data?", a: "Simplex", options: ["Full duplex", "Simplex", "Duplex", "F/full duplex"] },
      { q: "Which layer in the OSI model is responsible for carrying frames between adjacent nodes?", a: "Data link", options: ["Network", "Transport", "Data link", "Physical"] },
      { q: "A set of rules or procedures that govern how data is shared or sent over a communication media.", a: "Protocol", options: ["Protocol", "Memorandum", "Handover", "Handshake"] },
      { q: "Which layer in the OSI model is responsible for log-in and log-out procedure?", a: "Session", options: ["Session", "Network", "Application", "Transport"] },
      { q: "Which layer in the OSI model is responsible for route determination and selection?", a: "Network", options: ["Physical", "Transport", "Data link", "Network"] },
      { q: "What internet protocol is used to map a known IP address to an unknown MAC address?", a: "ARP", options: ["ICMP", "UDP", "RARP", "ARP"] },
      { q: "Which layer in the OSI model is responsible for format and code conversion services?", a: "Presentation", options: ["Transport", "Application", "Presentation", "Session"] },
      { q: "Which of the following is one of the protocols found at the transport layer?", a: "UDP", options: ["UCP", "UDP", "TDC", "TDP"] },
      { q: "Which data flow or transmission mode allows for bidirectional flow of data simultaneously?", a: "Full duplex", options: ["Simplex", "F/full duplex", "Full duplex", "Duplex"] },
      { q: "An agency of the United Nations whose duties include setting standards for various areas within the communication field. Formerly known as CCITT, it establishes standards to ensure compatibility of telecommunication equipment of different manufacturers.", a: "ITU", options: ["ITU", "IANA", "ISO", "IEEE"] },
      { q: "Which among the physical topologies is considered to be the most reliable?", a: "Mesh", options: ["Star", "Bus", "Ring", "Mesh"] },
      { q: "Which layer in the OSI model is responsible for providing user services such as email and file transfer?", a: "Application", options: ["Transport", "Application", "Network", "Session"] },
      { q: "Recent developments in the multimedia applications has increased the number of users and the amount of time each user spends on the network. What application/platform uses television over IP?", a: "PPLive", options: ["Telephony", "Skype", "YouTube", "PPLive"] },
      { q: "In 1967, at an Association for Computing Machinery (ACM) meeting, ARPA of the USA National Defense presented its ideas for the ARPANET... What does ARPANET mean?", a: "Advanced Research Projects Agency Network", options: ["Advanced Research Protocols Agency Network", "Advanced Research Projects Automatic Network", "Advanced Retransmission Protocols Agency Network", "Advanced Research Projects Agency Network"] },
      { q: "Recent developments in the multimedia applications has increased the number of users and the amount of time each user spends on the network. What application/platform uses video over IP?", a: "YouTube", options: ["Telephony", "Skype", "YouTube", "PPLive"] },
      { q: "It is a group of network devices that allow communication between various connected devices that covers smaller areas such as home, office or schools.", a: "LAN", options: ["LAN", "MAN", "WAN", "Ethernet"] },
      { q: "It is a network bigger than a LAN and covers a city or large campus. It connects several smaller networks in that area.", a: "MAN", options: ["LAN", "MAN", "WAN", "Ethernet"] },
      { q: "Recent developments in the multimedia applications has increased the number of users and the amount of time each user spends on the network. What application/platform uses voice over IP?", a: "Telephony", options: ["Telephony", "Skype", "YouTube", "PPLive"] },
      { q: "In the OSI model, error correction and retransmission are performed by the:", a: "Data link and Transport layer", options: ["Physical and data link layer", "Data link and Network layer", "Data link and Session layer", "Data link and Transport layer"] },
      { q: "In the OSI model, providing independence from different data representation is performed by the:", a: "Presentation layer", options: ["Transport Layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "In the OSI model, establishing, managing, and terminating sessions are performed by the:", a: "Session layer", options: ["Transport Layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "In the OSI model, reliable process-to-process delivery is performed by the:", a: "Transport layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer"] },
      { q: "In the OSI model, format and code conversion services are performed by the:", a: "Presentation layer", options: ["Transport Layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "TCP/IP model does not have __ layer but OSI model have this layer.", a: "Session layer", options: ["Transport layer", "Session layer", "Network layer", "Application layer"] },
      { q: "In the OSI model, route determination is performed by the:", a: "Network layer", options: ["Physical layer", "Transport layer", "Data link layer", "Network layer"] },
      { q: "In the OSI model, responsibility for carrying frames between adjacent nodes is performed by the:", a: "Data link layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer"] },
      { q: "In the OSI model, defining frames is performed by the:", a: "Data link layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer"] },
      { q: "In the OSI model, route selection is performed by the:", a: "Network layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer"] },
      { q: "In the OSI model, Interface to transmission media is performed by the:", a: "Physical layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer"] },
      { q: "In the OSI model, mechanical, electrical, and functional interface is performed by the:", a: "Physical layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer", "E (Unknown extra option)"] },
      { q: "In the OSI model, flow control is (are) performed by the:", a: "Data link and Transport layer", options: ["Physical and data link layer", "Data link and Network layer", "Data link and Session layer", "Data link and Transport layer"] },
      { q: "In the OSI model, providing user services is performed by the:", a: "Application layer", options: ["Transport Layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "In the OSI model, ensuring reliable transmission of data is (are) performed by the:", a: "Data link and Transport layer", options: ["Physical and data link layer", "Data link and Network layer", "Data link and Transport layer", "Data link and Session layer"] },
      { q: "The OSI model used in data communications is developed by", a: "ISO", options: ["FCC", "IEEE", "ISO", "TCP/IP"] },
      { q: "Federal Communications Commission (FCC) is a regulatory agency... In the Philippines, regulation is primarily vested in", a: "NTC", options: ["IECEP", "IEEE Phil. Section", "NTC", "DICT"] },
      { q: "Which topology has all its nodes connected directly to one center point and has no other connections between nodes?", a: "Star", options: ["Ring", "Star", "Bus", "Mesh"] },
      { q: "An Internet standard is a thoroughly tested specification... Upon recommendation from the Internet authorities, a draft may be published as an RFC. What does RFC mean?", a: "Request for Comment", options: ["Request for Comment", "Request for Connection", "Request for Control", "Repetition for Connection"] },
      { q: "It refers to the variation in packet delay for streaming audio or video packets.", a: "Jitter", options: ["Noise", "Quality of service (QoS)", "Jitter", "Burst"] },
      { q: "It is the biggest type of network, covering very large areas like countries or even the whole world. The internet is its most famous example.", a: "WAN", options: ["LAN", "MAN", "WAN", "Ethernet"] },
      { q: "Recent developments in the multimedia applications has increased the number of users and the amount of time each user spends on the network. What application/platform uses view sharing?", a: "Skype", options: ["Telephony", "Skype", "YouTube", "PPLive"] },
      { q: "In the OSI model, access for the end user is performed by the", a: "Application layer", options: ["Transport Layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "In the OSI model, transmission of bits across the medium is performed by the", a: "Physical layer", options: ["Physical layer", "Network layer", "Data link layer", "Transport layer"] },
      { q: "In the OSI model, communication with user's application program is performed by the", a: "Application layer", options: ["Transport layer", "Session layer", "Presentation layer", "Application layer"] }
    ],

    HW_CABLING_TOOLS: [
      { q: "What diagnostic utility tool determines the route to a destination by sending Internet Control Message Protocol (ICMP) echo packets to the destination?", a: "Tracert", options: ["Tracert", "Ping", "Nslookup", "Ipconfig", "ipconfig/all"] },
      { q: "It is a basic, yet popular, Windows network command-line utility used to display the basic TCP/IP network configuration of a computer.", a: "Ipconfig", options: ["Nslookup", "Ipconfig", "Tracert", "ping"] },
      { q: "The ping command operates by sending ICMP echo request packets. What does ping stand for?", a: "Packet internet groper", options: ["Protocol internet groper", "Packet internet groper", "Protocol industry group", "Packet instruction group"] },
      { q: "It is a network administration command-line tool used to retrieve all TCP/IP network information and configuration of a computer including its MAC address, adapter description, and DHCP details.", a: "ipconfig/all", options: ["ipconfig/all", "Ping", "Tracert", "Nslookup", "ipconfig"] },
      { q: "It is a network administration command-line tool used for querying the Domain Name System (DNS) to obtain domain name or IP address mapping information.", a: "Nslookup", options: ["Nslookup", "Tracert", "ipconfig/all", "Ping"] },
      { q: "What basic network command is used to test a device’s network connectivity?", a: "ping", options: ["Ipconfig", "tracert", "Nslookup", "ping"] },
      { q: "What is an advantage that coaxial cable has over STP or UTP?", a: "It can run for a longer distance unboosted", options: ["It can run for a longer distance unboosted", "It is inexpensive.", "None of the choices.", "It is capable of achieving 10 Mbps to 100Mpbs"] },
      { q: "What type of connector is used for DSL connection?", a: "RJ-11", options: ["RJ-45", "F", "AUI", "RJ-11"] },
      { q: "What type of connector is used to connect a router and a cable system?", a: "F", options: ["RJ-11", "AUI", "F", "RJ-45"] },
      { q: "Which connector does a UTP use?", a: "RJ-45", options: ["BNC", "RJ-69", "RJ-45", "STP"] },
      { q: "A type of twisted pair cable used to connect a computer to a network hub/router.", a: "Straight-through", options: ["Coaxial", "Straight-through", "Crossover", "Rollover"] },
      { q: "A type of Ethernet cable used to connect computing devices of the same type (e.g., two computers) directly.", a: "Crossover", options: ["A straight-through", "Coaxial", "Rollover", "Crossover"] },
      { q: "What type of cable is used to connect a terminal and a console port?", a: "Rollover", options: ["Coaxial", "Rollover", "Crossover", "Straight-through"] },
      { q: "How many pairs of wires make up a UTP cable?", a: "4", options: ["6", "4", "2", "8"] },
      { q: "Which of the following devices is a component of a PC that connects it to the networking device?", a: "NIC card", options: ["NIC card", "Repeater", "Hub", "Bridge", "Gateway"] },
      { q: "It is an intelligent network device that has decision-making and switching capabilities whose basic function is to expedite traffic flow on networks.", a: "Switch", options: ["Hub", "Repeater", "Router", "Switch", "Bridge"] },
      { q: "Which among the following network devices is capable of storing MAC address tables?", a: "Switch", options: ["Bridge", "Router", "Hub", "Switch", "Gateway"] },
      { q: "The MAC address is made up of ______ bytes or octets identified by its hexadecimal code.", a: "6", options: ["8", "6", "4", "16"] },
      { q: "Which among the following network devices is used to connect two or more different LANs?", a: "Router", options: ["Switch", "Hub", "Repeater", "Router", "Bridge"] },
      { q: "The MAC address is made up of how many bits?", a: "48", options: ["128", "48", "64", "32"] },
      { q: "Which device takes data from one network device and broadcasts the same to all the devices in the network?", a: "Hub", options: ["Hub", "Modem", "Router", "Switch", "Bridge"] },
      { q: "What does the twisting of the wires do in a twisted-pair cable?", a: "It reduces noise problems.", options: ["It makes it thinner.", "It makes it less expensive.", "It reduces noise problems.", "It allows six pairs to fit in the space of four pairs."] },
      { q: "For which of the following would you not need to provide a crossover cable?", a: "Connecting routers to switches", options: ["Connecting uplinks between switches", "Connecting routers to switches", "Connecting hubs to switches", "None of the above."] },
      { q: "Which among the following is NOT a function of a repeater?", a: "Repeater regenerates the signal over different networks", options: ["Repeater regenerates the signal over different networks", "Repeater does not amplify the signal", "It operates at the physical layer (layer 1)", "It is a 2-port device"] },
      { q: "How does a switch identifies a PC or node connected to the network?", a: "Through its MAC address", options: ["Through its MAC address", "Through its IP address", "Through its port address", "Through its logical address"] },
      { q: "What is the information that is 'burned in' to a network interface card?", a: "MAC address", options: ["NIC", "MAC address", "Hub", "LAN"] },
      { q: "For a given mesh network topology as shown, how many cables/links and ports are needed?(Diagram shows 4 PCs connected in a full mesh)", a: "6 cables, 12 ports", options: ["6 cables, 12 ports", "12 cables, 6 ports", "6 cables, 6 ports", "12 cables, 12 ports"] },
      { q: "Six PCs are connected to a local area network via a hub. PC0 would like to send data packet to PC3. What series of operations illustrates the working principle of a hub?", a: "A-D-E-G-F-B-C", options: ["A-D-E-G-F-B-C", "A-D-E-F-G-B-C", "A-B-C-D-E-F-G", "A-B-E-G-F-D-C"] },
      { q: "Six PCs are connected to a local area network via a SWITCH. PC0 would like to send data packet to PC4. What series of operations illustrates the working principle of a switch?", a: "A-C-D-F", options: ["A-C-D-F", "A-B-C-D-E-F", "A-D-C-F", "A-B-D-C-E-F"] },
      { q: "What portion of the IP address 129.219.51.18 represents the network?", a: "129.219", options: ["129.219", "129", "14.1", "1"] },
      { q: "As a network administrator, your client wants you to suggest either a switch or hub to be used in a medium-sized network. Which device will you recommend to such network?", a: "Switch", options: ["Switch", "Hub", "Either switch or hub", "Neither switch or hub"] }
    ],

    IP_ADDRESSING_SUBNET: [
      { q: "In a classful IPv4 address, the address 238.34.2.1 belongs to", a: "D", options: ["A", "C", "B", "D"] },
      { q: "What portion of the classful IP address 154.19.2.7 is the network address?", a: "154.19", options: ["154.19.2", "154.19", "154.19.2.7", "154"] },
      { q: "What are the two parts of an IPv4 address?", a: "Network address and host address", options: ["Network address and host address", "Network address and MAC address", "Host address and MAC address", "MAC address and subnet mask"] },
      { q: "The network number plays what part in an IP address?", a: "It specifies the network to which the host belongs", options: ["It specifies the network to which the host belongs", "It specifies which node on the subnetwork is being addressed.", "It specifies which networks the device can communicate with.", "It specifies the identity of the computer on the network."] },
      { q: "What portion of the IP address 129.219.51.18 represents the host id?", a: "51.18", options: ["18", "129.219.51", "129.219", "51.18"] },
      { q: "How many bits are in an IPv4 address?", a: "32", options: ["32", "128", "64", "48"] },
      { q: "The following is a valid IPv4 address EXCEPT__", a: "75.45.301.14", options: ["114.34.2.8", "132.56.8.6", "75.45.301.14", "208.34.54.12"] },
      { q: "What is the maximum value of each octet in an IP address?", a: "255", options: ["64", "256", "0", "255"] },
      { q: "How many host addresses can be used in a Class C network?", a: "254", options: ["255", "253", "256", "254"] },
      { q: "What is the /n notation for Class D address?", a: "none", options: ["none", "/8", "/24", "/16"] },
      { q: "Write the given mask 255.255.224.0 in slash notation(/n).", a: "/19", options: ["/8", "/24", "/19", "/16"] },
      { q: "Write the given mask 255.255.240.0 in slash notation(/n).", a: "/20", options: ["/16", "/20", "/18", "/19"] },
      { q: "In how many octets is IPv6 address segregated or grouped into?", a: "16", options: ["32", "16", "6", "4"] },
      { q: "How many hexadecimal digits are in an IPv6 address?", a: "32", options: ["8", "32", "16", "64"] },
      { q: "IPv6 address contains 8 sections separated by a colon. How many bytes are there in each section?", a: "2", options: ["16", "4", "2", "8"] },
      { q: "Write the shortest form of the given IPv6 address: 0000:00BC:0000:0000:0000:0000:119A:C250", a: "0:BC::119A:C250", options: ["0:00BC:0: 0: 0: 0:119A:C250", "0:BC::119A:C250", "0:00BC::119A:C250", "0:BC::119A:C25"] },
      { q: "Write the shortest form of the given IPv6 address: 234A:0000:0000:0000:00BB:119A:A001:0000", a: "234A::BB:119A:A001:0", options: ["234A:0:0:0:BB:119A:A001:0", "234A::00BB:119A:A001:0", "234A:0:0:0:00BB:119A:A001:0", "234A::BB:119A:A001:0"] },
      { q: "Which among the following is not a valid IPv6 address?", a: "0:BC::119A:C25", options: ["234A:0:0:0:00BB:119A:A001:0", "0:00BC::119A:C250", "0:BC::119A:C25", "234A:0:0:0:BB:119A:A001:0"] },
      { q: "In a block of addresses, the IP address of one host is known to be 182.44.82.16/26. Find the number of addresses in this block.", a: "64", options: ["64", "32", "16", "256"] },
      { q: "In a block of addresses, the IP address of one host is known to be 25.34.12.56/16. Find the number of addresses in this block.", a: "65536", options: ["16", "65536", "16777216", "256"] },
      { q: "In a block of addresses, the IP address of one host is known to be 182.44.82.16/26. What is the first address (network address) in this block?", a: "182.44.82.0", options: ["182.44.82.01", "182.44.82.0", "182.44.82.63", "182.44.0.0"] },
      { q: "In a block of addresses, the IP address of one host is known to be 25.34.12.56/16. What is the first address (network address) in this block?", a: "25.34.0.0", options: ["25.34.255.255", "25.34.0.1", "25.34.0.0", "25.34.255.0"] },
      { q: "In a block of addresses, the IP address of one host is known to be 25.34.12.56/16. What is the last address (limited broadcast address) in this block?", a: "25.34.255.255", options: ["25.34.255.255", "25.34.0.255", "25.34.255.0", "25.255.255.255"] },
      { q: "In a block of addresses, the IP address of one host is known to be 182.44.82.16/26. What is the last address (limited broadcast address) in this block?", a: "182.44.82.63", options: ["182.44.255.255", "182.44.82.64", "182.44.82.255", "182.44.82.63"] },
      { q: "Find the new mask for subnet 4 (4 addresses) from the block 17.12.40.0/27.", a: "/30", options: ["/29", "/28", "/27", "/30"] },
      { q: "Find the new mask for subnet 2 (8 addresses) from the block 17.12.40.0/27.", a: "/29", options: ["/30", "/28", "/27", "/29"] },
      { q: "Find the new mask for subnet 1 (16 addresses) from the block 17.12.40.0/27.", a: "/28", options: ["/29", "/30", "/28", "/27"] },
      { q: "The RIR is an organization that manages the allocation and registration of Internet number resources... RIR stands for:", a: "Regional Internet Registries", options: ["Regional Internal Registries", "Registries Internet Regional", "Regional Internet Registries", "Registries Internal Regional"] },
      { q: "The IP address space is managed globally by the IANA... IANA stands for:", a: "Internet Assigned Numbers Authority", options: ["Internet Assigned Numbers Authority", "Internal Assigned Numbers Authority", "Internet Associative Numbers Authoritative", "Internal Associative Numbers Authority"] }
    ],

    LAW_RA10844: [
      { q: "When was RA No. 10844 signed into law?", a: "May 23, 2016", options: ["May 23, 2015", "October 9, 2015", "May 23, 2016", "March 26, 2015"] },
      { q: "What important role of ICT is stated in the Declaration of Policy of RA 10844?", a: "Information and Communication in nation-building", options: ["Information and Communication in nation-building", "Digital Infrastructure", "Automation and Robotics", "Development of Networks"] },
      { q: "In what areas should ICT be available and accessible according to RA 10844?", a: "Areas not adequately served by the private sector", options: ["Industrial Zones", "Private sectors", "Areas not adequately served by the private sector", "Urban cities"] },
      { q: "What should ICT infrastructures be according to RA 10844?", a: "Strategic, reliable, cost-efficient, and citizen-centric", options: ["Built only for telecom companies", "Strategic, reliable, cost-efficient, and citizen-centric", "Focused mainly on big industrial zones", "Expensive and limited"] },
      { q: "Who leads the DICT, and what offices make up the Department proper?", a: "Secretary, Undersecretaries, Assistant Secretaries", options: ["Commissioner and ICT Board", "Local Government ICT Officers", "ICT Councils and Committees", "Secretary, Undersecretaries, Assistant Secretaries"] },
      { q: "Which agency was attached to the DICT but kept its regulatory powers?", a: "National Telecommunications Commission (NTC)", options: ["National Computer Center (NCC)", "National Telecommunications Commission (NTC)", "Cybercrime Investigation and Coordination Center (CICC)", "Telecommunications Office"] },
      { q: "Which office was transferred from DOST to the DICT?", a: "ICT Office (ICTO)", options: ["PAGASA", "ICT Office (ICTO)", "National Irrigation Authority", "Energy Development Office"] },
      { q: "Which of the following is one of the main functions of the DICT?", a: "Promote access to ICT and create ICT policies", options: ["Manage maritime systems", "Promote access to ICT and create ICT policies", "Regulate agricultural cooperatives", "Operate national power plants"] },
      { q: "How many Undersecretaries are allowed under the DICT structure?", a: "Three", options: ["One", "Two", "Three", "Four"] },
      { q: "What is DICT's role in cybersecurity under RA 10844?", a: "Implement and coordinate cybersecurity policies", options: ["Arrest cybercriminals", "Implement and coordinate cybersecurity policies", "Ban private encryption", "Give cybersecurity services only to private firms"] }
    ],

    LAW_RA11363: [
      { q: "What government body was created by RA 11363?", a: "Philippine Space Agency (PhilSA)", options: ["Philippine Space Council", "Department of Space Science", "Philippine Space Agency (PhilSA)", "National Research Council"] },
      { q: "What does \"PhilSA\" stand for?", a: "Philippine Space Agency", options: ["Philippine Satellite Authority", "Philippine Space Administration", "Philippine Space Agency", "Philippine Science Agency"] },
      { q: "Which year was the Philippine Space Act approved?", a: "2019", options: ["2017", "2018", "2019", "2020"] },
      { q: "Who is the Chairperson of the Philippine Space Council?", a: "President of the Philippines", options: ["Secretary of Science and Technology", "Secretary of National Defense", "Director General of PhilSA", "President of the Philippines"] },
      { q: "PhilSA is attached to which office for policy coordination?", a: "Office of the President", options: ["Department of Science and Technology", "Office of the President", "Department of National Defense", "Senate of the Philippines"] },
      { q: "What is the main role of PhilSA?", a: "Plan and promote the national space program", options: ["Regulate airline operations", "Plan and promote the national space program", "Conduct military intelligence missions", "Supervise telecommunications companies"] },
      { q: "Which government office confirms the appointment of the PhilSA Director General?", a: "Commission on Appointments", options: ["Supreme Court", "Department of Budget and Management", "Senate Committee on Science and Technology", "Commission on Appointments"] },
      { q: "How long after publication does the Act take effect?", a: "Fifteen (15) days", options: ["Immediately", "Ten (10) days", "Fifteen (15) days", "Thirty (30) days"] },
      { q: "How much was the initial operating fund of the PhilSA?", a: "P1 billion", options: ["P500 million", "P1 billion", "P2 billion", "P10 billion"] },
      { q: "The Philippine Space Development Fund is administered by whom?", a: "Director General of PhilSA", options: ["Secretary of Finance", "Philippine Space Council", "Director General of PhilSA", "Department of Budget and Management"] }
    ],

    LAW_RA11934: [
      { q: "What is the official short title of Republic Act No. 11934?", a: "Subscriber Identity Module (SIM) Registration Act", options: ["SIM Card Law", "Subscriber Identity Module (SIM) Registration Act", "Mobile Phone Registration Act", "Telecommunications Security Act"] },
      { q: "Who signed Republic Act No. 11934 into law, and on what date?", a: "Pres. Ferdinand Marcos Jr. on October 10, 2022", options: ["Pres. Rodrigo Duterte on April 14, 2022", "Pres. Ferdinand Marcos Jr. on October 10, 2022", "Pres. Ferdinand Marcos Jr. on December 27, 2022", "Pres. Rodrigo Duterte on September 19, 2022"] },
      { q: "According to Section 4 of RA 11934, how many days from the effectivity of the Act were existing SIM subscribers required to register their SIMs?", a: "180 days, extendable by 120 days", options: ["90 days, extendable by 60 days", "120 days, extendable by 90 days", "180 days, extendable by 120 days", "365 days, non-extendable"] },
      { q: "Which of the following information is NOT required for individual SIM registration under Section 5?", a: "Educational background", options: ["Full name", "Date of birth", "Educational background", "Address"] },
      { q: "How long must PTEs retain SIM registration data after an end-user deactivates their mobile number?", a: "10 years", options: ["3 years", "5 years", "10 years", "Indefinitely"] },
      { q: "For tourist SIM cards registered by foreign nationals visiting the Philippines, what is the validity period before automatic deactivation?", a: "30 days", options: ["15 days", "30 days", "60 days", "90 days"] },
      { q: "What is the penalty for 'spoofing' a registered SIM under Section 11(e)?", a: "Imprisonment of no less than 6 years or fine of P200,000, or both", options: ["Imprisonment of 6 months to 2 years or fine of P100,000 to P300,000", "Imprisonment of no less than 6 years or fine of P200,000, or both", "Fine of P500,000 to P4,000,000", "Imprisonment of 6 months to 6 years or fine of P100,000 to P300,000"] },
      { q: "Under what circumstances can PTEs disclose subscriber information according to Section 9?", a: "With written consent of the subscriber or in compliance with a court order upon finding of probable cause", options: ["Upon request from any government agency", "With written consent of the subscriber or in compliance with a court order upon finding of probable cause", "Whenever the PTE deems it necessary for security purposes", "Upon request from telecommunications companies"] },
      { q: "How should minors register their SIM cards according to Section 5(d)?", a: "Registration must be under the name of the minor's parent or guardian with their consent", options: ["Minors cannot register SIM cards under any circumstances", "Minors can register directly using their birth certificate", "Registration must be under the name of the minor's parent or guardian with their consent", "Minors can register using their school ID only"] },
      { q: "What is the maximum penalty for breach of confidentiality under Section 11(b)?", a: "Fine of P4,000,000", options: ["Fine of P1,000,000", "Fine of P2,000,000", "Fine of P4,000,000", "Imprisonment of 6 years and fine of P500,000"] }
    ],

    LAW_RA3846: [
      { q: "What is required before a person may legally operate any radio transmitting equipment in the Philippines?", a: "A radio operator certificate and station license", options: ["A barangay permit", "A radio operator certificate and station license", "A certificate of calibration only", "A municipal communication clearance"] },
      { q: "Which of the following is allowed under RA 3846 without requiring a station license?", a: "Operating a household radio receiver", options: ["Operating a household radio receiver", "Broadcasting over a homemade radio transmitter", "Transmitting Morse code as a hobby", "Constructing a commercial radio relay system"] },
      { q: "Under RA 3846, when can the government take temporary control of radio communications?", a: "During periods of war, emergency, or crisis", options: ["When a new president is elected", "During periods of war, emergency, or crisis", "When radio ratings decline", "Whenever new frequencies are assigned"] },
      { q: "Which of the following is prohibited under RA 3846 unless proper authorization is granted?", a: "Possession of any radio transmitter", options: ["Listening to FM radio music", "Possession of any radio transmitter", "Owning a battery-powered receiver", "Selling headphones for radio sets"] },
      { q: "What is the maximum validity period of a radio station license under RA 3846?", a: "3 years", options: ["1 year", "2 years", "3 years", "5 years"] },
      { q: "Which of the following is NOT one of the powers of the Secretary of Commerce and Communications under RA 3846?", a: "Grant citizenship to applicants", options: ["Assign radio frequencies", "Classify radio stations", "Issue operator licenses", "Grant citizenship to applicants"] },
      { q: "Under RA 3846, licenses cannot be transferred to a firm whose capital stock is _ % owned or controlled by aliens.", a: "20%", options: ["5%", "10%", "20%", "50%"] },
      { q: "In what situations may the President or Governor-General cause the closing of radio stations?", a: "During war, public peril, calamity, or disaster", options: ["Only during wartime", "During war, public peril, calamity, or disaster", "Whenever the government deems necessary", "During election periods only"] },
      { q: "What constitutes each day of continuous violation?", a: "A separate offense subject to penalties", options: ["A warning period", "A grace period", "A separate offense subject to penalties", "A minor infraction"] },
      { q: "Under Section 7, who are authorized to intercept radio messages?", a: "Persons authorized by the Secretary of Commerce and Communication", options: ["Any law enforcement officer", "Only the Secretary of Commerce and Communication", "Persons authorized by the Secretary of Commerce and Communication", "Anyone with proper radio equipment"] }
    ],

    LAW_RA7925: [
      { q: "RA 7925 is primarily known as which of the following laws in the Philippines?", a: "Public Telecommunications Policy Act", options: ["Electronic Commerce Act", "Public Telecommunications Policy Act", "Cybercrime Prevention Act", "Data Privacy Act"] },
      { q: "In what year was RA 7925 enacted to reform the Philippine telecommunications sector?", a: "1995", options: ["1986", "1990", "1995", "2001"] },
      { q: "One of the main objectives of RA 7925 was to transform the telecommunications market from a monopoly into which type of environment?", a: "Open and competitive market", options: ["Nationalized system", "Open and competitive market", "Government-only service", "Non-profit cooperative system"] },
      { q: "RA 7925 sought to encourage which of the following to help modernize the telecommunications industry?", a: "Private sector investment and innovation", options: ["Sole government ownership", "Private sector investment and innovation", "Foreign military support", "Elimination of all private companies"] },
      { q: "Under RA 7925, which government body is primarily tasked with regulating the telecommunications sector and enforcing the law's provisions?", a: "National Telecommunications Commission (NTC)", options: ["National Telecommunications Commission (NTC)", "National Privacy Commission (NPC)", "Department of Science and Technology (DOST)", "National Economic and Development Authority (NEDA)"] },
      { q: "A key policy under RA 7925 is to promote 'universal access.' What does this mainly refer to in the context of telecommunications?", a: "Wider availability of basic telecommunications services nationwide", options: ["Free devices for all citizens", "Priority service for urban centers only", "Limiting service to licensed engineers", "Wider availability of basic telecommunications services nationwide"] },
      { q: "RA 7925 aims to protect subscribers primarily through which of the following regulatory goals?", a: "Enforcing service quality and fair rates", options: ["Ensuring only one dominant provider", "Enforcing service quality and fair rates", "Preventing foreign investment", "Enforcing service quality and fair rates"] },
      { q: "To foster competition, RA 7925 encourages which practice among service providers?", a: "Interconnection among networks", options: ["Exclusive franchises without oversight", "Anti-competitive pricing agreements", "Interconnection among networks", "Blocking rival networks' calls"] },
      { q: "The policy direction of RA 7925 regarding technology can best be described as which of the following?", a: "Promoting modernization and technological innovation", options: ["Promoting modernization and technological innovation", "Restricting the use of modern technologies", "Maintaining only analog systems", "Banning foreign-made equipment"] },
      { q: "For ECE professionals, RA 7925 is important because it:", a: "Defines the legal and regulatory environment for telecom systems they design and maintain", options: ["Replaces engineering licensure requirements", "Defines the legal and regulatory environment for telecom systems they design and maintain", "Eliminates the need for compliance with technical standards", "Limits engineers to government employment only"] }
    ],

    LAW_RA12234: [
      { q: "What is the primary objective of Republic Act 12234 (Konektadong Pinoy Act)?", a: "To expand nationwide access to affordable and reliable internet service", options: ["To privatize telecommunications companies", "To expand nationwide access to affordable and reliable internet service", "To restrict foreign investment in ICT", "To regulate radio broadcast frequencies"] },
      { q: "Under the Konektadong Pinoy Act, which sector is mandated to lead the expansion of internet connectivity in underserved areas?", a: "DICT", options: ["DOST", "DICT", "NTC", "DepEd"] },
      { q: "RA 12234 prioritizes which areas for immediate digital infrastructure development?", a: "Geographically isolated and disadvantaged areas (GIDAS)", options: ["Business districts and financial zones", "Tourist destinations", "Geographically isolated and disadvantaged areas (GIDAS)", "Entertainment and gaming zones"] },
      { q: "What does 'DTIP' mean?", a: "Data Transmission Industry Participant", options: ["Data Transmission Industry Participant", "Digital Telephone Internet Provider", "Department of Technology and Internet Policy", "Direct Television Internet Package"] },
      { q: "The Konektadong Pinoy Act directs the government to establish digital infrastructure using which of the following technologies?", a: "A mix of fiber-optic, wireless, and satellite technologies", options: ["Only fiber-optic networks", "Only copper wire networks", "A mix of fiber-optic, wireless, and satellite technologies", "Radio-only access networks"] },
      { q: "Which government agency regulates telecommunications entities that will participate in the Konektadong Pinoy programs?", a: "National Telecommunication Commission (NTC)", options: ["Department of Energy", "National Telecommunication Commission (NTC)", "Department of Agriculture", "National Economic Development Authority"] },
      { q: "RA 12234 requires the government to promote digital inclusion. What does digital inclusion primarily refer to?", a: "Ensuring all Filipinos have access to internet and digital literacy", options: ["Limiting the number of internet users", "Ensuring all Filipinos have access to internet and digital literacy", "Requiring schools to teach only computer coding", "Restricting ICT jobs to licensed engineers"] },
      { q: "Under the Act, DICT is authorized to collaborate with which sectors to improve nationwide connectivity?", a: "Government agencies, private sector, and international partners", options: ["Only local government units", "Only private telcos", "Government agencies, private sector, and international partners", "Agricultural cooperatives only"] },
      { q: "Which policy means that when roads or big projects are built, they should put conduits underground at the same time so DITPs and other relevant entities can later put cables inside without digging the road again?", a: "Dig Once Policy", options: ["Open Access Policy", "Cable Management Policy Framework", "Dig Once Policy", "Pre-installation Cooperation Policy"] },
      { q: "What is emphasized in RA 12234 regarding internet access in public areas?", a: "Public areas should have free, reliable, and secure internet access", options: ["All public Wi-Fi must be paid", "Public Wi-Fi should be removed to reduce data privacy risks", "Public areas should have free, reliable, and secure internet access", "Only LGUs are allowed to provide public Wi-Fi"] }
    ],

    LAW_RA9292: [
      { q: "What is the primary purpose of RA 9292?", a: "To modernize the practice of electronics engineering and protect the profession", options: ["To regulate telecommunication companies", "To modernize the practice of electronics engineering and protect the profession", "To create the DICT", "To regulate importation of electronic devices"] },
      { q: "Who composes the Professional Regulatory Board of Electronics Engineering?", a: "1 chairman and 2 members", options: ["1 chairman and 4 members", "1 chairman and 3 members", "1 chairman and 2 members", "2 chairmen and 3 members"] },
      { q: "The Board of ECE is under which government agency?", a: "PRC", options: ["NTC", "DICT", "PRC", "DOST"] },
      { q: "Which of the following is NOT a category of professionals under RA 9292?", a: "Master Electrician (ME)", options: ["Electronics Engineer (ECE)", "Master Electrician (ME)", "Electronics Technician (ECT)", "Professional Electronics Engineer (PECE)"] },
      { q: "Who is authorized to sign and seal Electronics Engineering designs and plans?", a: "Professional Electronics Engineer", options: ["Any engineering graduate", "Electronics Technician", "Electronics Engineer", "Professional Electronics Engineer"] },
      { q: "Which of the following requires a PECE, not just an ECE?", a: "Preparing and signing electronics engineering documents", options: ["Repairing radio equipment", "Preparing and signing electronics engineering documents", "Installing basic CCTV systems", "Conducting electronics training"] },
      { q: "What is the minimum required experience (in years) before an ECE can apply for PECE?", a: "7 years", options: ["1 year", "2 years", "4 years", "7 years"] },
      { q: "Which of the following is within the scope of practice of Electronics Engineers?", a: "Designing analog and digital electronic circuits", options: ["Operating heavy electrical machinery", "Designing analog and digital electronic circuits", "Civil construction inspection", "Drafting architectural plans"] },
      { q: "Who is allowed to operate and maintain electronics equipment under RA 9292?", a: "Both ECE and ECT", options: ["Electronics Technician", "Electronics Engineer", "Both ECE and ECT", "Any trained worker"] },
      { q: "What is the penalty for practicing ECE or ECT without a valid license?", a: "Fine + imprisonment", options: ["6 months imprisonment only", "Fine only", "Fine + imprisonment", "Community service"] },
      { q: "Which agency grants the Certificate of Registration after passing the licensure exam?", a: "PRC", options: ["NTC", "PRC", "DICT", "DOST"] },
      { q: "What document legally authorizes a person to practice ECE or ECT?", a: "Certificate of Registration & PRC ID", options: ["Diploma", "Certificate of Good Moral Character", "Certificate of Training", "Certificate of Registration & PRC ID"] },
      { q: "Which of the following is a prohibited act under RA 9292?", a: "Using the ECE title without passing the board", options: ["Teaching electronics engineering subjects", "Using the ECE title without passing the board", "Designing communication systems", "Repairing computers"] },
      { q: "Which of the following is TRUE about Electronics Technicians (ECT)?", a: "They assist engineers in technical operations", options: ["They can sign engineering designs", "They assist engineers in technical operations", "They must hold a master’s degree", "They can perform PECE functions"] },
      { q: "What is the validity period of the PRC ID for ECE and ECT?", a: "3 years", options: ["1 year", "2 years", "3 years", "5 years"] },
      { q: "Which body prepares and administers the ECE and ECT licensure examinations?", a: "PRC Board of ECE", options: ["CHED", "DICT", "PRC Board of ECE", "NTC"] },
      { q: "What is required for renewal of PRC ID under RA 9292?", a: "CPE/CPD compliance", options: ["Only payment of fee", "CPE/CPD compliance", "Retaking an exam", "Passing a review course"] },
      { q: "Under RA 9292, who can practice the full scope of Electronics Engineering including sealing documents?", a: "PECE", options: ["ECE", "ECT", "PECE", "Any licensed engineer"] },
      { q: "What is one power of the Board of ECE?", a: "Suspend or revoke licenses", options: ["Regulate telcos", "Issue Certificates of Good Conduct", "Suspend or revoke licenses", "Draft curriculum for CHED"] },
      { q: "RA 9292 repealed which older law?", a: "RA 5734", options: ["RA 10844", "RA 8292", "RA 5734", "RA 7925"] }
    ],

    // EXERCISE_OSI_TCP_IP: kept as an exercises pool but duplicates removed if already present in OSI_DATA_COMMS/IP_ADDRESSING_SUBNET
    // Only unique exercise questions that were not exact duplicates are kept here.
    EXERCISE_OSI_TCP_IP: [
      { q: "How many layers are there in the OSI model?", a: "7", options: ["4", "7", "6", "5"] },
      { q: "Identify the OSI layer that defines frames.", a: "Data link layer", options: ["Physical layer", "Data link layer", "Network layer", "Transport layer"] },
      { q: "Identify the OSI layer that performs transmission of bit stream across physical medium.", a: "Physical layer", options: ["Physical layer", "Data link layer", "Network layer", "Transport layer"] },
      { q: "Identify the OSI layer that performs process-to-process message delivery.", a: "Transport layer", options: ["Application layer", "Physical layer", "Data link layer", "Network layer", "Transport layer"] },
      { q: "Identify the OSI layer that establishes, manages and terminates sessions.", a: "Session layer", options: ["Transport layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "Identify the OSI layer that provides log-in and log-out procedures.", a: "Session layer", options: ["Transport layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "Identify the OSI layer that provides independence from different data representation", a: "Presentation layer", options: ["Transport layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "Identify the OSI layer that formats and codes conversion services.", a: "Presentation layer", options: ["Transport layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "Identify the OSI layer that provides access for the end user.", a: "Application layer", options: ["Network layer", "Data link layer", "Transport layer", "Application layer"] },
      { q: "Identify the OSI layer that communicates directly with user's application program.", a: "Application layer", options: ["Transport layer", "Session layer", "Presentation layer", "Application layer"] },
      { q: "A packet in TCP (Transmission Control Protocol) is called", a: "Segment", options: ["Segment", "Bits", "Frames", "Datagrams"] },
      { q: "The unit of data transfer between two devices using TCP software is called a", a: "Segment", options: ["Frames", "Packet", "Datagram", "Segment"] },
      { q: "A transportation unit in an SCTP protocol is termed as", a: "Packet", options: ["Datagram", "Frames", "Packet", "Segment"] },
      { q: "Process-to-process delivery at the transport layer needs two identifiers, IP address and the port number, at each end to make connection. The combination of an IP address and a port number is called a", a: "Socket address", options: ["Port address", "Logical address", "Physical address", "Socket address"] },
      { q: "Which protocol does not belong to the Transport layer?", a: "FTP", options: ["UDP", "SCTP", "FTP", "TCP"] },
      { q: "Which protocol does not belong to the Network layer?", a: "SMTP", options: ["RARP", "ARP", "ICMP", "SMTP", "IGMP"] },
      { q: "Which protocol does not belong to the Application layer?", a: "ARP", options: ["SMTP", "ARP", "DNS", "FTP", "SNMP"] },
      { q: "A network layer protocol that sends query and error reporting messages. It is a mechanism used by hosts and gateways to send notification of datagram problems back to the sender.", a: "ICMP (Internet Control Message Protocol)", options: ["RARP (Reverse Address Resolution Protocol)", "ARP (Address Resolution Protocol)", "IGMP (Internet Group Message Protocol)", "ICMP (Internet Control Message Protocol)", "IPv4 (Internet Protocol version 4)"] },
      { q: "A network layer protocol that allows a host to discover its internet address when it knows only its physical address. It is used when a computer is connected to a network for the first time or when a diskless computer is booted.", a: "RARP (Reverse Address Resolution Protocol)", options: ["IGMP (Internet Group Message Protocol)", "RARP (Reverse Address Resolution Protocol)", "ARP (Address Resolution Protocol)", "ICMP (Internet Control Message Protocol)", "IPv4 (Internet Protocol version 4)"] },
      { q: "On a typical physical network such as LAN, each device on a link is identified by a physical or station address, usually imprinted on the network interface card (NIC). What network layer protocol is used to find the physical address of the node when its IP address is known?", a: "ARP (Address Resolution Protocol)", options: ["ICMP (Internet Control Message Protocol)", "RARP (Reverse Address Resolution Protocol)", "IGMP (Internet Group Message Protocol)", "IPv4 (Internet Protocol version 4)", "ARP (Address Resolution Protocol)"] },
      { q: "A network layer protocol that is used to facilitate the simultaneous transmission of a message to a group of recipients. It is a management protocol that helps a multicast router create and update a list of loyal members related to each router interface.", a: "IGMP (Internet Group Message Protocol)", options: ["IPv4 (Internet Protocol version 4)", "ICMP (Internet Control Message Protocol)", "RARP (Reverse Address Resolution Protocol)", "IGMP (Internet Group Message Protocol)", "ARP (Address Resolution Protocol)"] },
      { q: ": A client/server, static configuration protocol in the application layer designed to provide physical address to logical address mapping.", a: "BOOTP (Bootstrap Protocol)", options: ["DHCP (Dynamic Host Configuration Protocol)", "SNMP (Simple Network Management Protocol", "IGMP (Internet Group Message Protocol)", "BOOTP (Bootstrap Protocol)", "SCTP (Stream Control Transmission Protocol)"] },
      { q: "A protocol that provides static and dynamic address location that can be manual or automatic.", a: "DHCP (Dynamic Host Configuration Protocol)", options: ["DHCP (Dynamic Host Configuration Protocol)", "IGMP (Internet Group Message Protocol)", "SCTP (Stream Control Transmission Protocol)", "BOOTP (Bootstrap Protocol)", "SNMP (Simple Network Management Protocol"] },
      { q: "It is a framework for managing devices in an internet using the TCP/IP protocol suite. It provides a set of fundamental operations for monitoring and maintaining an internet.", a: "SNMP (Simple Network Management Protocol)", options: ["SNMP (Simple Network Management Protocol)", "DNS (Domain Name System)", "TELNET (Terminal Network)", "FTP (File Transfer Protocol)", "SMTP (Simple Mail Transfer Protocol)"] },
      { q: "The Internet Assigned Number Authority (IANA) has divided the port numbers into three ranges: (1) the ports ranging from 0 to 1023 are assigned and controlled by IANA and are called the well-known ports; (2) the ports ranging from 1024 to 49,151 are not assigned or controlled by IANA although they can be registered with IANA to prevent duplication. These are known as registered ports; and (3) the ports ranging from 49,152 to 65, 535 are neither controlled nor registered. They can be used by any process. These are known as the dynamic or ephemeral ports. HTTP uses the services of TCP on well-known", a: "port 80", options: ["port 20", "port 80", "port 53", "port 21"] },
      { q: "FTP uses two well-known TCP ports: _____ for control connection and _____ for data connection.", a: "port 21, port 20", options: ["port 21, port 20", "port 21, port 80", "port 20, port 53", "port 20, port 21"] },
      { q: "DNS can use the services of UDP or TCP using the well-known", a: "port 53", options: ["port 53", "port 80", "port 20", "port 21"] },
      { q: "It is the leading information retrieval service of the Internet (the worldwide computer network). It is a repository of information linked together from points all over the world. It was a project initiated by CERN (European Laboratory for Particle Physics) to create a system to handle distributed resources necessary for scientific research.", a: "WWW (World Wide Web)", options: ["IPv6", "WAN (Wide Area Network)", "WWW (World Wide Web)", "URL (Uniform Resource Locator)"] },
      { q: "It is a standard for specifying any kind of information on the internet. It defines the protocol, host computer, port and path. It is a unique identifier used to locate a resource on the Internet and commonly referred to also as a web address.", a: "URL (Uniform Resource Locator)", options: ["URL (Uniform Resource Locator)", "IP Address", "MAC Address", "WWW (World Wide Web)"] },
      { q: "A client/server application that provides name services for other applications. It enables the use of application-layer addresses, such as an email address, instead of network layer logical addresses. It is a protocol that can be used in different platforms.", a: "DNS (Domain Name System)", options: ["TELNET (Terminal Network", "SNMP (Simple Network Management Protocol)", "SMTP (Simple Mail Transfer Protocol)", "FTP (File Transfer Protocol)", "DNS (Domain Name System)"] },
      { q: "It is a language for creating web pages. It allows the use only of ASCII characters both for the main text and the formatting instructions. In this way, every computer can receive the whole document as an ASCII document. The main text is the data and the formatting instructions can be used by the browser to format the data.", a: "Hypertext Markup Language (HTML)", options: ["Java Server Pages (JSP)", "Hypertext Markup Language (HTML)", "Hypertext Preprocessor (PHP)", "Active Server Pages (ASP)"] },
      { q: "The following are technologies used for creating dynamic documents (or server-site dynamic documents) using scripts EXCEPT:", a: "Hypertext Markup Language (HTML)", options: ["Hypertext Markup Language (HTML)", "Java Server Pages (JSP) which uses the Java language", "Hypertext Preprocessor (PHP) which uses the Perl language", "Active Server Pages (ASP) which uses Visual Basic"] },
      { q: "It is a protocol used mainly to access data on the World Wide Web. It functions as a combination of FTP and SMTP.", a: "HTTP (Hypertext Transfer Protocol)", options: ["HTML (Hypertext Markup Language)", "TELNET (Terminal Network)", "DNS (Domain Name System)", "HTTP (Hypertext Transfer Protocol)", "SNMP (Simple Network Management Protocol)"] },
      { q: "It is the formal application layer protocol that defines the message transfer agent (MTA) client and server in the Internet. It defines how commands and responses must be sent back and forth.", a: "SMTP (Simple Mail Transfer Protocol)", options: ["TELNET (Terminal Network", "FTP (File Transfer Protocol)", "DNS (Domain Name System)", "SMTP (Simple Mail Transfer Protocol)", "SNMP (Simple Network Management Protocol)"] },
      { q: "It is the standard mechanism provided by TCP/IP for copying a file from one host to another. It differs from other client/server applications in that it establishes two connections between the hosts. One connection is used for data transfer, the other for control information (commands and responses).", a: "FTP (File Transfer Protocol)", options: ["TELNET (Terminal Network)", "DNS (Domain Name System)", "SNMP (Simple Network Management Protocol)", "SMTP (Simple Mail Transfer Protocol)", "FTP (File Transfer Protocol)"] },
      { q: "It is the standard TCP/IP protocol for virtual terminal service as proposed by the International Organization for Standards (ISO). It is a general-purpose client/server application program that enables the establishment of a connection to a remote system in such a way that the local terminal appears to be a terminal at the remote system. It allows the user to log on to a remote machine, giving the user access to the remote system.", a: "TELNET (Terminal Network)", options: ["SMTP (Simple Mail Transfer Protocol", "TELNET (Terminal Network)", "FTP (File Transfer Protocol)", "SNMP (Simple Network Management Protocol)", "DNS (Domain Name System)"] }
    ],

    MOCK_BOARD_MATH: [
        { q: "The Z-transform is primarily used in.", a: "Discrete-time systems", options: ["Continuous systems", "Discrete-time systems", "Analog circults", "Static structures"] },
        { q: "A ladder 10 feet long is leaning against a vertical wall. If the bottom of the ladder slides away from the wall at a rate of 2 ft/s, how fast is the top of the ladder sliding down the wall when the bottom is 6 feet from the wall?", a: "3/2 ft/s", options: ["3/2 ft/s", "6/5 π/s", "4/3 ft/s", "8/3 ft/s"] },
        { q: "How many petals are in the graph of a rose curve with an equation of r = 100cos(4θ).", a: "8", options: ["8", "16", "4", "100"] },
        { q: "Which of the following best describes a function?", a: "A relation where each Input has exactly one output", options: ["A relation where each Input has exactly one output", "A relation where Inputs can have multiple outputs", "A process that always increases values", "A set of ordered pairs with no restrictions"] },
        { q: "A Fourier series represents a function as:", a: "A sum of sine and cosine terms", options: ["A product of polynomials", "A sum of sine and cosine terms", "A sum of exponentials only", "A series of square waves"] },
        { q: "If f'(x) changes from negative to positive at x = c, then c is a:", a: "Local minimum", options: ["Local maximum", "Local minimum", "Point of inflection", "Critical obstruction"] },
        { q: "The general solution of a first-order differential equation typically contains:", a: "One arbitrary constant", options: ["No constant", "No derivatives", "One arbitrary constant", "Two arbitrary constants"] },
        { q: "Find the equation of the tangent line to the curve x³ + y³ = 2xy at point (1, 1).", a: "x+y-2=0", options: ["x+y-2=0", "c-y=0", "y-x+2=0", "x+y=0"] },
        { q: "The solution to a differential equation with an initial condition is called:", a: "Particular solution", options: ["General solution", "Particular solution", "Exact solution", "Homogeneous solution"] },
        { q: "A related rates problem involves:", a: "Relating changes in two quantities over time", options: ["Solving simultaneous equations", "Relating changes in two quantities over time", "Maximizing functions", "Minimizing quadratic forms"] },
        { q: "Determine the area enclosed by the two curves y = x² and y² = 8x.", a: "8/3", options: ["8/3", "12/3", "10/3", "14/3"] },
        { q: "The solution curve to dy/dx = x + y is:", a: "An exponential-type curve", options: ["A straight line", "A family of parabolas", "An exponential-type curve", "A trigonometric function"] },
        { q: "Find the length of the curve y = (x-1)^(3/2) from x = 1 to x = 5.", a: "9.073", options: ["12.412", "7.106", "16.521", "9.073"] },
        { q: "Water is leaking from a tank at the rate of R(t) = 5arctan(t/5) gallons per hour, where t is the number of hours since the leak began. To the nearest gallon, how much water will leak out during the first day?", a: "124", options: ["7", "24", "12", "124"] },
        { q: "What is the solution to a 4th order differential equation with characteristic roots r = 0, 0, 2, -2?", a: "y = C₁ + C₂x + C₃e^(2x) + C₄e^(-2x)", options: ["y = C₁ + C₂e^(4x) + C₃e^(-x) + C₂x", "y = C₁x + C₂x² + C₃e^(2x) + C₄e^(-2x)", "y = C₁e^(2x) + C₂e^(-2x) + C₃e^(2x) + C₄e^(-2x)", "y = C₁ + C₂x + C₃e^(2x) + C₄e^(-2x)"] },
        { q: "What is the integral of sec²x dx?", a: "tan x + C", options: ["sec x + c", "csc x + C", "tan x + C", "cot x + C"] },
        { q: "Given the differential equation dy/dx = 3x², y(0) = 4. What is the value of y(2)?", a: "12", options: ["8", "16", "12", "20"] },
        { q: "Find the integral of dx / (1 + x²).", a: "tan⁻¹(x) + C", options: ["ln|1 + x²| + C", "tan⁻¹(x) + C", "sec⁻¹(x) + C", "x(1 + x²) + C"] },
        { q: "Which is not a valid interpretation of the derivative?", a: "Maximum value of a function", options: ["Slope of the tangent line", "Instantaneous rate of change", "Maximum value of a function", "Linear approximation of the function"] },
        { q: "The integral of a derivative f'(x) is always:", a: "f(x) - c", options: ["t(x) + c", "Conty", "f'(x) + c", "f(x) - c"] },
        { q: "Given the Bernoulli differential equation dy/dx + y = y². With v = 1/y, what is the resulting linear equation in v?", a: "dv/dx - v = -1", options: ["dv/dx - v = -1", "dv/dx + v = 1", "dv/dx + v = -1", "dv/dx - v = 1"] },
        { q: "The Laplace transform of a second derivative is:", a: "s²F(s) - sf(0) - f'(0)", options: ["s²F(s) - sf(0) - f'(0)", "sF(s) - f(0)", "s*F(s)", "F''(s)"] },
        { q: "What is the general solution of dy/dx = (1/x)ln x?", a: "y = ln(ln x) + c", options: ["y = ln(ln x) + c", "y = ln x + c", "y = ln(ln(ln x)) + C", "y = 1/ln x + c"] },
        { q: "Find the integral of xeˣ dx.", a: "xeˣ - eˣ + C", options: ["xeˣ - eˣ + C", "eˣ + C"] },
        { q: "Determine the surface area obtained by rotating y = ∛x from y = 1 to y = 2 about the y-axis.", a: "199.48", options: ["199.48", "197.26", "198.373", "196.15"] },
        { q: "A first order separable differential equation means:", a: "Its variables can be separated on different sides of the equation.", options: ["Its variables can be separated on different sides of the equation.", "It is homogeneous.", "It has unique solutions.", "It contains higher derivatives."] },
        { q: "The Laplace transform of a signal often involves complex numbers to represent:", a: "Frequency-domain behavior", options: ["Static values", "Frequency-domain behavior", "Time decay only", "Initial conditions"] },
        { q: "Homogeneous first-order equations can be solved by:", a: "Substitution y/x", options: ["Euler's method", "Substitution y/x", "Laplace transform", "Taylor series"] },
        { q: "Determine the surface area obtained by rotating y = √(9 - x²) from x = -2 to x = 2 about the x-axis.", a: "24π", options: ["21π", "23π", "22π", "24π"] },
        { q: "Which of the following ODEs is separable?", a: "y' = xy", options: ["y' + y tan x = 0", "y' = xy", "y' + y/x = sin x", "y' = x + y"] },
        { q: "Determine the Laplace transform of f(t) = 2sin(4t) - 3cos(4t).", a: "(8 - 3s) / (s² + 16)", options: ["(8 - 3s) / (s² + 4)", "(2s - 12) / (s² + 4)", "(8 - 3s) / (s² + 16)", "(2s - 12) / (s² + 15)"] },
        { q: "Which of the following equations is not linear?", a: "dy/dx + y² = x", options: ["dy/dx + y = x", "dy/dx + x²y = sin x", "dy/dx + y² = x", "y' + 3y = 0"] },
        { q: "Find the Laplace transform of x(t) = sinh(4t), t > 0.", a: "4 / (s² - 16)", options: ["4 / (s² + 16)", "4 / (s² - 16)", "s / (s² + 16)", "s / (s² - 16)"] },
        { q: "Find the area bounded by the curve x² - 12x - 5y + 11 = 0 and the x-axis.", a: "33.33 u²", options: ["23.33 u²", "43.33 u²", "33.33 u²", "53.33 u²"] },
        { q: "A point where concavity is changing is called a:", a: "Inflection point", options: ["Critical point", "Stationary point", "Inflection point", "Minima"] },
        { q: "Which of the following best defines a complex number?", a: "A number with both real and imaginary parts", options: ["A number that cannot be expressed in decimal form", "A number with both real and imaginary parts", "A number greater than zero", "A purely imaginary number"] },
        { q: "Water is poured into a conical tank at a constant rate of 12 ft³/min. The tank stands with its point down, with a height of 20 ft and a radius of 10 ft. How fast is the water level rising when the water is 8 ft deep?", a: "0.239 ft/min", options: ["0.239 ft/min", "3.820 ft/min", "0.060 ft/min", "0.119 ft/min"] },
        { q: "Given the area bounded by the curve y² = x, the line x = 4 and the x-axis. What is the volume generated when this area is revolved about the y-axis?", a: "80.4 cu. units", options: ["78.1 cu. units", "62.2 cu. units", "80.4 cu. units", "54.7 cu. units"] },
        { q: "Which of the following equations is a variable separable differential equation?", a: "(y + x²y)dx = (4x + xy²)dy", options: ["(y + x²y)dx = (4x + xy²)dy", "2xy dx = (1 + xy)dy", "(x + y)dx - 2y dy = 0", "y² dx + (2x - 3y)dy = 0"] },
        { q: "What does it mean for a series to converge?", a: "Its sum approaches a finite limit", options: ["Its terms alternate signs", "Its sum approaches a finite limit", "There series has a factorial", "The sequence of terms is bounded"] },
        { q: "Find the surface area of the torus formed by revolving a circle x² + (y-1)² = 9 about the line x = 5.", a: "60π²", options: ["30π", "30π²", "60m", "60π²"] },
        { q: "The Laplace transform is most useful in solving:", a: "Differential equations", options: ["Algebraic equations", "Differential equations", "Trigonometric Identities", "Statistical models"] }
    ],

    MOCK_BOARD_EST: [
        { q: "In the Shannon limit for information capacity theorem, if the bandwidth is reduced by 4 times while maintaining the signal-to-noise ratio of the transmission medium at its original ratio, what is the effect on its maximum capacity?", a: "Reduced by 4 times", options: ["Reduced by two", "Reduced by 4 times", "Doubled", "Increased by four times"] },
        { q: "Typically, the velocity factor of the materials used in transmission lines range from", a: "0.6 to 0.9", options: ["0.6 to 0.9", "1.0 to 0.9", "0.1 to 0.5", "0.6 to 0.8"] },
        { q: "An AM transmitter has a carrier power of 1000 W. The total sideband power Is measured to be 250 W (single-tone modulation). Find the modulation index.", a: "0.7", options: ["0.5", "0.8", "0.7", "1.0"] },
        { q: "Bit rate is the number of bits per second. Baud rate is the number of signal elements per second. In the analog transmission of digital data, the baud rate is", a: "less than or equal to", options: ["equal to the bit rate..", "less than", "greater than", "less than or equal to"] },
        { q: "Overmodulation in AM primarily causes:", a: "Envelope distortion", options: ["Reduced bandwidth", "Higher carrier power", "Envelope distortion", "Lower sideband power"] },
        { q: "What property distinguishes digital radio systems from conventional analog communications system?", a: "The nature of the modulating signal", options: ["The type of carrier used", "The nature of the modulating signal", "The type of modulation of data to be used", "The nature of the transmitter and receiver used"] },
        { q: "In digital modulation, the levels of a signal may reduce the reliability of the system.", a: "Increasing", options: ["Increasing", "maintaining", "decreasing", "changing"] },
        { q: "In an FM system, the maximum frequency deviation Is 75 kHz and the highest modulating frequency is 15 kHz. Determine the modulation Index.", a: "5", options: ["2", "4", "3", "5"] },
        { q: "The result whenever the sampling rate is less than twice the highest audio frequency.", a: "Allasing", options: ["Frequency synthesis", "Overload distortion", "Allasing", "Quantizing noise"] },
        { q: "In PCM the samples are dependent on", a: "Quantization level", options: ["Time", "Frequency", "Quantization level", "Interval between quantization level"] },
        { q: "Analog to digital conversion includes:", a: "Sampling & Quantization", options: ["Sampling", "Sampling & Quantization", "Quantization", "None of the choices"] },
        { q: "The dynamic range of a system is the ratio of", a: "the strongest transmittable signal to the weakest discernible signal", options: ["the strongest transmittable signal to the weakest discernible signal", "the maximum rate of conversion to the minimum rate of conversion", "the maximum bits per sample to the minimum bits per sample", "None of the cholces"] },
        { q: "What is true about aliasing and foldover distortion?", a: "They are the same thing", options: ["they are two types of sampling error", "you can have one or the other, but not both", "Aliasing is a technique to prevent foldover distortion", "They are the same thing"] },
        { q: "The Immediate result of sampling is:", a: "PAM", options: ["a sample alias", "PCM", "PAM", "PDM"] },
        { q: "A type of modulation scheme that changes the amplitude of the carrler with respect to the modulating signal.", a: "AM", options: ["PM", "FM", "AM", "SM"] },
        { q: "Solve for the characteristic Impedance of a line having a capacitance of 1100 pF and an inductance of 11 μΗ.", a: "100 ohms", options: ["90 ohms", "110 ohms", "100 ohms", "75 ohms"] },
        { q: "The basic modulator and demodulator circuits in PSK are,", a: "balanced modulators", options: ["PLLS", "shift registers", "balanced modulators", "linear summers"] },
        { q: "A reflection coefficient of 0.782 has a return loss of how many dB?", a: "2.14 dB", options: ["3.14 dB", "1.14 dB", "2.14 dB", "0.14 dB"] },
        { q: "The envelope of which of the following remains constant?", a: "FM", options: ["AM", "DSB-FC", "FM", "SSB"] },
        { q: "The signals which are obtained by encoding each quantized signal into a digital word is called as:", a: "PCM signal", options: ["PAM signal", "Sampling and quantization", "PCM signal", "FM signal"] },
        { q: "A communication link uses an AM DSB-SC system and a standard AM system with the same message and same peak envelope power. Which has lower carrier-power requirement for the same information?", a: "DSB-SC", options: ["Standard AM", "Cannot be determined", "DSB-SC", "Both equal"] },
        { q: "A device that converts a balanced line to an unbalanced line of a transmission system?", a: "balun", options: ["hybrid", "directional coupler", "stub", "balun"] },
        { q: "The maximum peak-to-peak value of an AM envelope is 16 V and the minimum is 4 V. Determine the modulation index.", a: "0.6", options: ["0.25", "0.6", "0.5", "0.75"] },
        { q: "The velocity factor for a transmission line", a: "depends on the dielectric constant of the material used", options: ["depends on the dielectric constant of the material used", "Increases the velocity along the transmission line", "is governed by the skin effect", "is higher for a solid dielectric than for air"] },
        { q: "The bandwidth required for conventional AM with a maximum modulating frequency ' ' is:", a: "2fm", options: ["1m", "4f", "2fm", "fm / 2"] },
        { q: "Consider an extremely noisy channel in which the value of the signal-to-noise ratio is almost zero. In other words, the noise Is so strong that the signal is faint. For this channel the capacity is calculated as:", a: "zero", options: ["maximum", "half the bandwidth", "zero", "None of the choices"] },
        { q: "Modulation is used to", a: "Allow the use of practical antennas", options: ["Increase the carrier power", "Reduce the bandwidth used", "Allow the use of practical antennas", "Shorten the transmission channel"] },
        { q: "is the ratio of reflected voltage to the forward travelling voltage.", a: "reflection coefficient", options: ["SWR", "reflection coefficient", "VSWR", "ISWR"] },
        { q: "A Yagi-Uda antenna is designed to receive signals centered at 450 MHz. Calculate the length of the driven element", a: "0.3167 m", options: ["0.355 m", "0.453 m", "0.3167 m", "1.267 m"] },
        { q: "In an FM system, the maximum frequency deviation is 75 kHz and the highest modulating frequency Is 15 kHz. What is the bandwidth?", a: "180 kHz", options: ["90 kHz", "180 kHz", "150 kHz", "240 kHz"] },
        { q: "The transmitting antenna has a gain of 10 dB, and power output of 6000 W. Determine the ERP.", a: "60 kW", options: ["80 KW", "60 kW", "70 KW", "50 KW"] },
        { q: "A communication link uses an AM DSB-SC system and a standard AM system with the same message and same peak envelope power. Which has better power efficiency?", a: "DSB-SC", options: ["Standard AM", "Both equal", "DSB-SC", "Cannot be determined"] },
        { q: "An antenna has a radiation resistance of 72 , a loss resistance of 80 and a power gain of 16. Find the directivity gain.", a: "17.78", options: ["19", "17.78", "15.67", "13.33"] },
        { q: "Compared to AM broadcasting, FM broadcasting typically uses:", a: "Higher carrier frequencies and higher bandwidth,", options: ["Lower carrier frequencies and lower bandwidth", "Higher carrier frequencies and higher bandwidth,", "Lower carrier frequencies and higher bandwidth", "Higher carrier frequencies and lower bandwidth"] },
        { q: "What is the orientation of the electric field of an antenna to the earth's surface and antenna structure?", a: "Polarization", options: ["Vertical", "Collimation", "Polarization", "Horizontal"] },
        { q: "The following are considered primary line constants except", a: "complex propagation constant", options: ["conductance", "resistance", "capacitance", "complex propagation constant"] },
        { q: "In communications system, noise is most likely to affect the signal at the?", a: "Recelver", options: ["Transmitter", "Channel", "Recelver", "Antenna"] },
        { q: "Determine the characteristic Impedance for a quarter wavelength transformer that is used to match a section of the transmission line with the characteristic Impedance of 75 to 80 load.", a: "77.46 ohms", options: ["75 ohms", "67 ohms", "25 ohms", "77.46 ohms"] },
        { q: "Demodulation is done at the:", a: "Receiver", options: ["Transmitter", "Channel", "Receiver", "Antenna"] },
        { q: "Width measured In degrees of a major lobe between end of the lobe at which the relative power is one half (-3dB) its value from the peak of the lobe.", a: "Beamwidth", options: ["Beamwidth", "Wavelength", "Radiation", "Bandwidth"] },
        { q: "In frequency modulation, the modulation index is defined as:", a: "Ratio of frequency deviation to message frequency", options: ["Ratlo of carrier frequency to message frequency", "Ratio of message amplitude to carrier amplitude", "Ratio of frequency deviation to message frequency", "Product of frequency deviation and message frequency"] },
        { q: "We need to send 265 kbps over a noiseless channel with a bandwidth of 20 kHz. How many signal levels do we need?", a: "128 levels", options: ["96 levels", "4 levels", "128 levels", "64 levels"] },
        { q: "An AM signal has carrler power of 500 W and is 50% modulated by a single sine wave. What is the total power?", a: "562.5 W", options: ["531.25 W", "625 W", "562.5 W", "750 W"] },
        { q: "A 500 lossless line terminated in a purely resistive load has a voltage standing-wave ratio of 3. Find all the possible values of .", a: "150 ohms and 15 ohms", options: ["100 ohms and 20 ohms", "150 ohms and 15 ohms", "200 ohms and 24 ohms", "300 ohms and 22 ohms"] },
        { q: "In PM, when the modulating signal amplitude increases, the:", a: "Phase deviation Increases", options: ["Phase deviation Increases", "Phase deviation decreases", "Carrier amplitude Increases", "Carrier frequency Increases linearly"] },
        { q: "A carrier of frequency 1 MHz Is AM by a 5 kHz tone with m = 0.8. Carrier power is 100 W. Which set shows all frequency components?", a: "0.995 MHz, 1 MHz, 1.005 MHz", options: ["1 MHz only", "0.995 MHz, 1 MHz, 1.005 MHz", "0.995 MHz and 1.005 MHz only", "5 kHz and 1 MHz only"] },
        { q: "Shannon's theorem describes the parameters affecting communication channel capacity. In the Shannon's formula a low value of SNR indicates that", a: "There is a need to install repeater", options: ["Transmission is most likely error free", "More capacity can be accommodated", "There is a need to install repeater", "Data is 100% error free"] },
        { q: "Which of the following is true for FM but not for AM?", a: "Amplitude limiting Improves noise performance", options: ["Information is carried in the amplitude of the carrier", "Envelope detection is sufficient for demodulation", "Amplitude limiting Improves noise performance", "Carrier amplitude must vary with the message"] },
        { q: "If a cable has a velocity factor of 0.8, how long would it take a signal to travel 3000 kilometers along the cable?", a: "12.5 ms", options: ["12.5 ms", "75 με", "15 ms", "88 μs"] },
        { q: "A DSB-SC system and an SSB system transmit the same baseband signal with the same transmitted power. Which system occuples less bandwidth?", a: "SSB", options: ["DSB-SC", "SSB", "Both occupy the same bandwidth", "Depends on modulation Index"] }
    ]

  };

  // Derived LAW_ALL pool
  data.LAW_ALL = [
    ...(data.LAW_RA10844 || []),
    ...(data.LAW_RA11363 || []),
    ...(data.LAW_RA11934 || []),
    ...(data.LAW_RA3846 || []),
    ...(data.LAW_RA7925 || []),
    ...(data.LAW_RA12234 || []),
    ...(data.LAW_RA9292 || [])
  ];

  // Combined ALL topics
  data.ALL = [
    ...(data.OSI_DATA_COMMS || []),
    ...(data.HW_CABLING_TOOLS || []),
    ...(data.IP_ADDRESSING_SUBNET || []),
    ...(data.EXERCISE_OSI_TCP_IP || []),
    ...(data.MOCK_BOARD_MATH || []),
    ...(data.MOCK_BOARD_EST || []),
    ...data.LAW_ALL
  ];

  return data;
})();